#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="monitoring"
output_off
prepare_service defaults single
check_container_initialized
check_service_initialized init
liftoff

case "${CONTAINER_MONITORING_BACKEND}" in
    "zabbix" )
        print_debug "Trying to execute Container Monitoring Backend Zabbix"
        case "${ZABBIX_AGENT_TYPE,,}" in
            "1" | "c" | "classic" | "legacy" | "old" )
                print_debug "Starting classic Zabbix Agent"
                zabbix_command="zabbix_agentd"
                zabbix_agent_type="classic"
            ;;
            "2" | "m" | "n" | "modern" | "new" )
                print_debug "Starting modern Zabbix agent"
                zabbix_command="zabbix_agent2"
                zabbix_agent_type="modern"
            ;;
            * )
                print_debug "No known Zabbix agent type selected"
            ;;
        esac

        print_debug "Zabbix Agent - Adding Autoregister Configuration '$(grep -h "# Autoregister=" "${ZABBIX_CONFIG_PATH}"/"${ZABBIX_CONFIG_FILE}".d/*.conf | cut -d = -f2 | xargs | tr " " ":" | sed 's/^/:/' | sed 's/$/:/')'"
        sed -i "/HostMetadata/d" "${ZABBIX_CONFIG_PATH}"/"${ZABBIX_CONFIG_FILE}"
        if var_true "${ZABBIX_ENABLE_AUTOREGISTER}" ; then
            print_debug "Zabbix Agent - Enabling Auto Register"
            sed -i "/^Include=.*/i HostMetadata=$(grep -h "# Autoregister=" "${ZABBIX_CONFIG_PATH}"/"${ZABBIX_CONFIG_FILE}".d/*.conf | cut -d = -f2 | xargs | tr " " ":" | sed 's/^/:/' | sed 's/$/:/')" "${ZABBIX_CONFIG_PATH}"/"${ZABBIX_CONFIG_FILE}"
            if var_true "${ZABBIX_ENABLE_AUTOREGISTER_DNS}" ; then
                print_debug "Zabbix Agent - Enabling Auto Register by DNS"
                if [ -n "${ZABBIX_AUTOREGISTER_DNS_NAME}" ] ; then
                    print_debug "Zabbix Autoregsiter DNS: Using ${ZABBIX_AUTOREGISTER_DNS_NAME} as hostname"
                else
                    ZABBIX_AUTOREGISTER_DNS_NAME="${ZABBIX_HOSTNAME}${ZABBIX_AUTOREGISTER_SUFFIX}"
                fi
                sed -i "/HostInterface=.*/d" "${ZABBIX_CONFIG_PATH}"/"${ZABBIX_CONFIG_FILE}"
                sed -i "/^Include=.*/i HostInterface=${ZABBIX_AUTOREGISTER_DNS_NAME}" "${ZABBIX_CONFIG_PATH}"/"${ZABBIX_CONFIG_FILE}"
            fi
        fi

        chown -R "${ZABBIX_USER}":root "${ZABBIX_CONFIG_PATH}"
        chmod -R 0755 "${ZABBIX_CONFIG_PATH}"

        if var_true "${CONTAINER_ENABLE_FIREWALL}" && var_true "${CONTAINER_ENABLE_FAIL2BAN}" ; then
            while [ ! -S "/var/run/fail2ban/fail2ban.sock" ] ; do
                sleep 1
            done
             setfacl -m g:fail2ban:rwx /var/run/fail2ban/fail2ban.sock
        fi

        print_start "Starting Zabbix Agent (${zabbix_agent_type}) ${ZABBIX_VERSION}"
        output_on
        silent exec s6-setuidgid "${ZABBIX_USER}" ${zabbix_command}  -c "${ZABBIX_CONFIG_PATH}"/"${ZABBIX_CONFIG_FILE}" -f
    ;;
esac
