#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/02-cron ]; then
        echo ' '
        sleep 120
        echo '59 23 * * * logrotate -f /etc/logrotate.d/* >/dev/null 2>&1' >>/assets/cron/crontab.txt
	mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/02-cron
fi

echo '** Starting cron'
/usr/bin/crontab /assets/cron/crontab.txt
exec /usr/sbin/crond -f -l 8


