#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="scheduling"
output_off
prepare_service
check_container_initialized
check_service_initialized init

if var_true "${CONTAINER_ENABLE_LOGROTATE}" ; then
    print_debug "[logrotate] Setting Logrotate retention days after all services have finished initializing"
    mkdir -p /etc/logrotate.d
    print_debug "[logrotate] Moving files from /assets/logrotate to /etc/logrotate.d"
    cp -R /assets/logrotate/* /etc/logrotate.d
    sed -i "s|rotate .*|rotate ${LOGROTATE_RETAIN_DAYS}|g" /etc/logrotate.d/*
    sed -i "s|//|/|g" /etc/logrotate.d/*
    chown -R root:root /etc/logrotate.d
    chmod -R 0644 /etc/logrotate.d
fi

liftoff

case "${CONTAINER_SCHEDULING_BACKEND}" in
    "cron" )
      if [ "${SCHEDULING_LOG_TYPE,,}" = "file" ]; then
        cron_log_file="-L ${SCHEDULING_LOG_LOCATION}/cron.log"
      fi

      print_debug "Parsing all files from ${CONTAINER_SCHEDULING_LOCATION}"
      temp_crontab=$(date +%s)
      echo 'MAILTO=""' > $temp_crontab
      if dir_empty "${CONTAINER_SCHEDULING_LOCATION}" ; then echo "# Intentionally empty" > "${CONTAINER_SCHEDULING_LOCATION}"/empty ; fi;
      sed "/#/d" "${CONTAINER_SCHEDULING_LOCATION}"/* | awk 'NF' >> /tmp/.container/cron/${temp_crontab}
      silent crontab -r
      crontab /tmp/.container/cron/${temp_crontab}

      print_start "Starting cron"
      os=$(cat /etc/os-release |grep ^ID= | cut -d = -f2)
      case ${os} in
        "alpine" )
          output_on
          exec /usr/sbin/crond -f -l ${SCHEDULING_LOG_LEVEL} ${cron_log_file}
        ;;
        "debian" | "ubuntu" )
          output_on
          exec /usr/sbin/crond -f -l ${SCHEDULING_LOG_LEVEL} ${cron_log_file}
        ;;
        esac
    ;;
esac
