#!/command/with-contenv bash

source /assets/functions/00-container
output_off
# shellcheck disable=SC2034
PROCESS_NAME="permissions"

## Legacy
if var_true "${ENABLE_PERMISSIONS}" ; then
    CONTAINER_ENABLE_PERMISSIONS=TRUE
    elif var_false "${ENABLE_PERMISSIONS}" ; then
    CONTAINER_ENABLE_PERMISSIONS=FALSE
fi
##

if var_true "${DEBUG_PERMISSIONS}" ; then
    CONTAINER_LOG_LEVEL="DEBUG"
fi

### Enable or Disable permissions
if var_true "${CONTAINER_ENABLE_PERMISSIONS}" ; then
    print_debug "Enabling permissions features"

    # change uid in /etc/passwd with the ones defined in Docker's environment settings
    unames="$(set -o posix ; set | sort | grep -e '^USER_' | sed "s|^USER_||g" | tr '[:upper:]' '[:lower:]' | tr ' ' '\n') "
    unames+="$(set -o posix ; set | sort | grep -e '^CONTAINER_USER_' | sed "s|^CONTAINER_USER_||g" | tr '[:upper:]' '[:lower:]' | tr ' ' '\n')"

    for upair in $unames; do
        uname=$(echo "${upair}" | cut -d = -f 1)
        uid=$(echo "${upair}" | cut -d = -f 2)
        if grep -e "^${uname}" /etc/passwd > /dev/null; then
           _userexists=true
        elif grep -e "^${uname/_/-}" /etc/passwd > /dev/null; then
           _userexists=true
           uname=${uname/_/-}
        fi
        if [ "${_userexists}" = true ] ; then
            ouid=$(grep -e "^${uname}" /etc/passwd | awk -F: '{print $3}')

            print_debug "Changing user '${u}' to uid '${uid}' from '${ouid}'"
            sed -i "s|${uname}:x:${ouid}:|${uname}:x:${uid}:|g" /etc/passwd
        fi
    done

    # Change gid in /etc/group and /etc/passwd with the ones defined in Docker's environment settings
    groups="$(set -o posix ; set | sort | grep -e '^GROUP_' | sed "s|^GROUP_||g" | tr '[:upper:]' '[:lower:]' | tr ' ' '\n' | sed '/add_.*/d' ) "
    groups+="$(set -o posix ; set | sort | grep -e '^CONTAINER_GROUP_' | sed "s|^CONTAINER_GROUP_||g" | tr '[:upper:]' '[:lower:]' | tr ' ' '\n' | sed '/add_.*/d' ) "

    for gpair in $groups; do
        gname=$(echo "${gpair}" | cut -d = -f 1)
        gid=$(echo "${gpair}" | cut -d = -f 2)
        if grep -e "^${gname}" /etc/group > /dev/null; then
           _groupexists=true
        elif grep -e "^${gname/_/-}" /etc/group > /dev/null; then
           _groupexists=true
           gname=${gname/_/-}
        fi

        if [ "${_groupexists}" = true ] ; then
            opgid=$(grep -e "^${gname}" /etc/passwd | awk -F: '{print $4}')
            og=$(grep -e "^${gname}" /etc/group | awk -F: '{print $1}')
            oggid=$(grep -e "^${gname}" /etc/group | awk -F: '{print $3}')
            print_debug "Changing group '${gname}' to gid '${gid}' from '${oggid}'"
            sed -i "s|\(.*\):\(.*\):\(.*\):${opgid}:|\1:\2:\3:${gid}:|g" /etc/passwd
            sed -i "s|${og}:x:${oggid}|${og}:x:${gid}|g" /etc/group
        fi
    done

    # Add users defined in Docker's environment settings to groups in /etc/group
    groupsadd="$(set -o posix ; set | sort | grep -e '^GROUP_ADD_' | sed 's|^GROUP_ADD_||g' | tr '[:upper:]' '[:lower:]' ) "
    groupsadd+="$(set -o posix ; set | sort | grep -e '^CONTAINER_GROUP_ADD_' | sed 's|^CONTAINER_GROUP_ADD_||g' | tr '[:upper:]' '[:lower:]' )"

    for gapair in $groupsadd; do
        gname=$(echo "${gapair}" | cut -d = -f1 )
        if grep -e "^${gname}" /etc/group > /dev/null; then
           _groupexists=true
        elif grep -e "^${gname/_/-}" /etc/group > /dev/null; then
           _groupexists=true
           gname=${gname/_/-}
        fi

        if [ "${_groupexists}" = true ] ; then
            uta=$(echo ${gapair} | cut -d = -f2 | tr ',' '\n')
            for userstogroup in ${uta} ; do
                print_debug "Adding user '${userstogroup}' to '${gname}'"
                os=$(cat /etc/os-release |grep ^ID= | cut -d = -f2)
                case ${os,,} in
                    "alpine" )
                        silent addgroup ${userstogroup} ${gname}
                    ;;
                    "debian" | "ubuntu" )
                        silent usermod -a -G ${gname} ${userstogroup}
                    ;;
                esac
            done
        fi
    done
fi

liftoff
output_on