#!/usr/bin/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="cron"
### Set Defaults
ENABLE_CRON=${ENABLE_CRON:-"TRUE"}

### Check to see if Enabled/Disabled
if [ "$ENABLE_CRON" = "FALSE" ] || [ "$ENABLE_CRON" = "false" ];  then
	print_warn "Disabling Cron"
	s6-svc -d /var/run/s6/services/`basename $0`
fi

liftoff