#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service single
PROCESS_NAME="logging"

output_off

if var_true "${CONTAINER_ENABLE_LOGROTATE}" ; then
    print_debug "Enabling log rotation"
    mkdir -p "${CONTAINER_SCHEDULING_LOCATION}"
    cat <<EOF > "${CONTAINER_SCHEDULING_LOCATION}"/logrotate
# Hardcoded in image in /etc/cont-init.d/$(basename "$0")
# Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')

59 23 * * * logrotate -f /etc/logrotate.d/* >/dev/null 2>&1
EOF
fi

if var_false "${CONTAINER_ENABLE_LOGSHIPPING}" ;  then
  print_notice "Disabling Log Shipping Functionality"
  service_stop "$(basename "$0")"
else
  case "${CONTAINER_LOGSHIPPING_BACKEND}" in
    "fluent-bit" | "fluentbit" )
        os=$(cat /etc/os-release |grep ^ID= | cut -d = -f2)
            case ${os} in
              "alpine" )
                archit="$(apk --print-arch)"
                case "$archit" in
                  x86_64)
                    case "$(cat /etc/os-release | grep VERSION_ID | cut -d = -f 2 | cut -d . -f 1,2)" in
                      3.11|3.12|3.13|3.14|3.15 )
                          :
                      ;;
                      *)
                        print_error "Sorry this functionality is not available on pre Alpine 3.11 releases"
                        service_stop "$(basename "$0")"
                        liftoff
                        exit
                      ;;
                    esac
                  ;;
                  *)
                    print_error "Sorry this functionality is not available on ${archit} architecture"
                    service_stop "$(basename "$0")"
                    liftoff
                    exit
                  ;;
                esac
              ;;
              "debian" )
                archit=$(dpkg --print-architecture) && \
                  case "$archit" in \
                    amd64)
                      :
                    ;;
		                *)
                    print_error "Sorry this functionality is not available on ${archit} architecture"
                    service_stop "$(basename "$0")"
                    liftoff
                    exit
                  ;;
                esac
              ;;
        esac

        if [ "${FLUENTBIT_SETUP_TYPE}" = "AUTO" ] || [ "${FLUENTBIT_SETUP_TYPE}" = "auto" ] ; then
          print_debug "[logship] Configuring Fluent-bit agent"
          truefalse_onoff FLUENTBIT_ENABLE_HTTP_SERVER
          truefalse_onoff FLUENTBIT_ENABLE_STORAGE_METRICS
          truefalse_onoff FLUENTBIT_STORAGE_CHECKSUM
          mkdir -p "${FLUENTBIT_STORAGE_PATH}"
          mkdir -p "${FLUENTBIT_LOG_PATH}"
          mkdir -p /etc/fluent-bit/conf.d
          cat <<EOF > /etc/fluent-bit/conf.d/do_not_delete.conf
# Don't delete this configuration file otherwise execution of fluent-bit will fail. It will not affect operation of your system or impact resources
[INPUT]
    Name   dummy
    Tag    ignore

[FILTER]
    Name grep
    Match ignore
    regex ignore ignore

[OUTPUT]
    Name   NULL
    Match  ignore
EOF

          for custom_parser in /etc/fluent-bit/parsers.d/*.conf ; do
            print_debug "[logship] Found additional parser for '$(echo "${custom_parser,,}" | sed "s|.conf||g")'"
            additional_parsers=$(echo "${additional_parsers}" ; cat<<EOF
    parsers_file ${custom_parser}
EOF
                                )
          done

          cat <<EOF > /etc/fluent-bit/fluent-bit.conf
## Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')

@INCLUDE conf.d/*.conf
[SERVICE]
    daemon       Off
    flush        ${FLUENTBIT_FLUSH_SECONDS}
    grace        ${FLUENTBIT_GRACE_SECONDS}
    http_listen  ${FLUENTBIT_HTTP_LISTEN_IP}
    http_port    ${FLUENTBIT_HTTP_LISTEN_PORT}
    http_server  ${FLUENTBIT_ENABLE_HTTP_SERVER}
    log_file     ${FLUENTBIT_LOG_PATH}/${FLUENTBIT_LOG_FILE}
    log_level    ${FLUENTBIT_LOG_LEVEL}
    plugins_file ${FLUENTBIT_CONFIG_PLUGINS}
    storage.backlog.mem_limit ${FLUENTBIT_STORAGE_BACKLOG_LIMIT}
    storage.checksum ${FLUENTBIT_STORAGE_CHECKSUM}
    storage.metrics ${FLUENTBIT_ENABLE_STORAGE_METRICS}
    storage.path ${FLUENTBIT_STORAGE_PATH}
    storage.sync ${FLUENTBIT_STORAGE_SYNC}
    parsers_file ${FLUENTBIT_CONFIG_PARSERS}
${additional_parsers}
EOF

##### Input Plugins
          case "${FLUENTBIT_MODE}" in
            "NORMAL" | "normal" )
              print_debug "[logship] Configuring Fluent-Bit for Normal/Client mode"
              #### Override by Environment Variables
              logshipenv=$(mktemp)
              set -o posix; set -f ; set | grep -E '^LOGSHIP_'| sed "s|LOGSHIP_||g" > "${logshipenv}"
              while IFS= read -r logship_entry; do
                logship_title="$(echo "${logship_entry}" | cut -d = -f1 | tr '[:upper:]' '[:lower:]' )"
                logship_value="$(echo "${logship_entry}" | cut -d = -f2 )"
                logship_value="$(echo "${logship_value:1:-1}")"
                if var_false "${logship_value}" ; then
                  print_debug "[logship] Disabling ${logship_title} Log Shipping"
                  cat <<EOF > "/etc/fluent-bit/conf.d/in_tail_${logship_title,,}.conf"
# Nulled Log Monitoring of ${logship_title}  generated by Environment Variable defined in Image build, or Runtime argument
# Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')
EOF
                  if [ -f "/etc/logrotate.d/${logship_title,,}" ] ; then
                    print_debug "[logship] Setting Logrotate value to skip for /etc/logrotate.d/${logship_title,,}"
                    sed -i "# logship: .*|# logship: ignore"
                  fi
                else
                  print_debug "[logship] Adding ${logship_title} with to be parsed by ${CONTAINER_LOGSHIPPING_BACKEND}"
                  cat <<EOF > "/etc/fluent-bit/conf.d/in_tail_${logship_title,,}.conf"
# Log File Monitoring created automatically generated by Environment Variable defined in Image build, or Runtime argument
# Entered Value: ${logship_value}
# Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')

[INPUT]
    Name        tail
    Path        ${logship_value}
    Path_Key    filename
    Tag         ${logship_title,,}

[FILTER]
    Name record_modifier
    Match ${logship_title,,}
    Record hostname $(hostname)
    Record container_name ${CONTAINER_NAME}
    Record product ${logship_title,,}

EOF
                fi
              done < "${logshipenv}"
              rm -rf "$logshipenv"
              set +f
              unset logshipenv logship_entry logship_value logship_title
              unset "${!LOGSHIP_@}"

              ## Defaults
              for d in /assets/defaults/* ; do
                if [ "$d" != "/assets/defaults/00-container" ] ; then
                      # shellcheck source=/assets/defaults/
                      source "$d"
                      logshipenv=$(mktemp)
                      set -o posix; set -f ; set | grep -E '^LOGSHIP_'| sed "s|LOGSHIP_||g" > "${logshipenv}"
                      while IFS= read -r logship_entry; do
                        logship_title="$(echo "${logship_entry}" | cut -d = -f1 | tr '[:upper:]' '[:lower:]')"
                        logship_value="$(echo "${logship_entry}" | cut -d = -f2 )"
                        logship_value="$(echo "${logship_value:1:-1}")"

                        if [ ! -f "/etc/fluent-bit/conf.d/in_tail_${logship_title,,}.conf" ] ; then
                          print_debug "[logship] Adding ${logship_title} with to parsed by ${CONTAINER_LOGSHIPPING_BACKEND}"
                          cat <<EOF > "/etc/fluent-bit/conf.d/in_tail_${logship_title,,}.conf"
# Log File Shipping created automatically generated by reading through defaults in /assets/defaults/*
# Entered Value: ${logship_value}
# Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')

[INPUT]
    Name        tail
    Path        ${logship_value}
    Path_Key    filename
    Tag         ${CONTAINER_NAME}_${logship_title,,}
EOF
                        else
                          print_debug "[logship] Skipping adding ${logship_title} as it already exists"
                        fi
                      done < "${logshipenv}"
                    rm -rf "$logshipenv"
                    set +f
                    unset logshipenv logship_entry logship_value logship_title
                    unset "${!LOGSHIP_@}"
                fi
              done
            ;;
            "PROXY" | "proxy" | "FORWARDER" | "forward" )
              print_debug "[logship] Configuring Fluent-Bit for Proxy/Forwarding Mode"
              cat <<EOF > /etc/fluent-bit/conf.d/in_forward.conf
[INPUT]
    Name forward
    Listen 0.0.0.0
    Port ${FLUENTBIT_FORWARD_PORT}
    Buffer_Chunk_Size ${FLUENTBIT_FORWARD_BUFFER_CHUNK_SIZE}
    Buffer_Max_Size   ${FLUENTBIT_FORWARD_BUFFER_MAX_SIZE}
EOF
            ;;
          esac

##### Output Plugins
          case "${FLUENTBIT_OUTPUT}" in
            "LOKI" | "loki" )
              if [ -n "${FLUENTBIT_OUTPUT_LOKI_USER}" ] ; then
                loki_user="    http_user              ${FLUENTBIT_OUTPUT_LOKI_USER}"
              fi

              if [ -n "${FLUENTBIT_OUTPUT_LOKI_PASS}" ] ; then
                loki_pass="    http_passwd            ${FLUENTBIT_OUTPUT_LOKI_PASS}"
              fi

              if [ -n "${FLUENTBIT_OUTPUT_LOKI_TENANT_ID}" ] ; then
                loki_tenant_id="    tenant_id              ${FLUENTBIT_OUTPUT_LOKI_TENANT_ID}"
              fi

              truefalse_onoff FLUENTBIT_OUTPUT_LOKI_TLS
              truefalse_onoff FLUENTBIT_OUTPUT_LOKI_TLS_VERIFY

              cat <<EOF > /etc/fluent-bit/conf.d/out_loki.conf
## Auto generated LOKI Output plugin for Fluent Bit
## Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')

[OUTPUT]
    name                   loki
    match                  *
    host                   ${FLUENTBIT_OUTPUT_LOKI_HOST}
    port                   ${FLUENTBIT_OUTPUT_LOKI_PORT}
    tls                    ${FLUENTBIT_OUTPUT_LOKI_TLS,,}
    tls.verify             ${FLUENTBIT_OUTPUT_LOKI_TLS_VERIFY,,}
    labels                 logshipper=${CONTAINER_NAME}
    Label_keys             \$hostname,\$container_name,\$product
${loki_user}
${loki_pass}
${loki_tenant_id}

EOF
            ;;
            "FLUENTD" | "fluentd" | "FORWARD" | "forward" )
              truefalse_onoff FLUENTBIT_OUTPUT_FORWARD_TLS
              truefalse_onoff FLUENTBIT_OUTPUT_FORWARD_TLS_VERIFY
              if [ ! -z "${FLUENTBIT_OUTPUT_FORWARD_SECRET}" ] ; then
                forward_secret="    Shared_Key    ${FLUENTBIT_OUTPUT_FORWARD_SECRET}"
              fi
              cat <<EOF > /etc/fluent-bit/conf.d/out_forward.conf
## Auto generated FluentD Forward Output plugin for Fluent Bit
## Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')

[OUTPUT]
    Name          forward
    Match         *
    Host          ${FLUENTBIT_OUTPUT_FORWARD_HOST}
    Port          ${FLUENTBIT_FORWARD_PORT}
    Self_Hostname ${CONTAINER_NAME}
    tls           ${FLUENTBIT_OUTPUT_FORWARD_TLS,,}
    tls.verify    ${FLUENTBIT_OUTPUT_FORWARD_TLS_VERIFY,,}
${forward_secret}
EOF
            ;;
            "NULL" | "null" )
              cat <<EOF > /etc/fluent-bit/conf.d/out_null.conf
## Auto generated NULL Output plugin for Fluent Bit
## Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')

[OUTPUT]
    Name null
    Match *
EOF
            ;;
          esac
        else
          print "[logship] Not auto configuring Fluent-Bit. Drop configuration files in /etc/fluent-bit/conf.d"
          cat <<EOF > /etc/fluent-bit/fluent-bit.conf
## This configuration file allows you to put your own configuration in /etc/fluent-bit/conf.d - Don't delete or it will fail :)
## Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')
@INCLUDE conf.d/*.conf
EOF
        fi
        create_logrotate fluentbit "${FLUENTBIT_LOG_PATH}"/"${FLUENTBIT_LOG_FILE}"
        print_notice "Container configured to ship logs via '${CONTAINER_LOGSHIPPING_BACKEND}'"
    ;;
    *)
      print_error "[logship] Unknown Log Shipping Backend"
      exit 1
    ;;
  esac

fi

output_on
liftoff
