#!/usr/bin/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="zabbix"
check_initialized
liftoff

### Start Zabbix
print_info "Starting Zabbix Agent"
silent exec s6-setuidgid zabbix zabbix_agentd -f
