#!/usr/bin/with-contenv bash

### Start Zabbix
sed -i -e "s/<ZABBIX_HOSTNAME>/$ZABBIX_HOSTNAME/g" /etc/zabbix/zabbix_agentd.conf       
mkdir -p /var/log/zabbix
chown -R zabbix /var/log/zabbix
echo ''
echo '*** Starting Zabbix..'

exec s6-setuidgid zabbix zabbix_agentd -f;

