#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="zabbix"
output_off
check_container_initialized
check_service_initialized init
liftoff
output_on

### Start Zabbix
print_info "Starting Zabbix Agent"
silent exec s6-setuidgid zabbix zabbix_agentd -f
