#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="smtp"
output_off
check_container_initialized
check_service_initialized init
liftoff

if [[ "$DEBUG_SMTP" = "TRUE" ]] || [[ "$DEBUG_SMTP" = "true" ]] ;  then
        print_info "Starting MailHog - Enabled at Port 1025, Map an exposed port and visit Visit http://127.0.0.1:8025 for Web Interface"
	silent exec s6-setuidgid mailhog MailHog;
fi
output_on
