#!/usr/bin/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="smtp"

check_initialized
liftoff

if [[ "$DEBUG_SMTP" = "TRUE" ]] || [[ "$DEBUG_SMTP" = "true" ]] ;  then
	print_info "Starting MailHog"
	silent exec s6-setuidgid mailhog MailHog;
fi