#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="smtp"
check_container_initialized
check_service_initialized init
liftoff

if [[ "$DEBUG_SMTP" = "TRUE" ]] || [[ "$DEBUG_SMTP" = "true" ]] ;  then
	print_info "Starting MailHog"
	silent exec s6-setuidgid mailhog MailHog;
fi